"""

Revision ID: 184c6c63a31a
Revises: db4f63b939b4
Create Date: 2026-02-27 17:21:14.407753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184c6c63a31a'
down_revision: Union[str, Sequence[str], None] = 'db4f63b939b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_labels',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'label_id', name='uq_issue_labels_issue_id_label_id')
    )
    op.create_index('ix_issue_labels_issue_id', 'issue_labels', ['issue_id'], unique=False)
    op.create_index('ix_issue_labels_label_id', 'issue_labels', ['label_id'], unique=False)
    op.create_table('change_request_issues',
    sa.Column('change_request_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_request_id', 'issue_id', name='uq_change_request_issues_cr_id_issue_id')
    )
    op.create_index('ix_change_request_issues_change_request_id', 'change_request_issues', ['change_request_id'], unique=False)
    op.create_index('ix_change_request_issues_issue_id', 'change_request_issues', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_change_request_issues_issue_id', table_name='change_request_issues')
    op.drop_index('ix_change_request_issues_change_request_id', table_name='change_request_issues')
    op.drop_table('change_request_issues')
    op.drop_index('ix_issue_labels_label_id', table_name='issue_labels')
    op.drop_index('ix_issue_labels_issue_id', table_name='issue_labels')
    op.drop_table('issue_labels')
    # ### end Alembic commands ###
