"""

Revision ID: 419cd4dc5e17
Revises: d835d546b329
Create Date: 2026-03-02 01:09:06.080971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419cd4dc5e17'
down_revision: Union[str, Sequence[str], None] = 'd835d546b329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('projects', 'is_archived', server_default=None)
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'is_archived')
    # ### end Alembic commands ###
