"""

Revision ID: 5d40a2277918
Revises: 736e4b523c6c
Create Date: 2026-03-03 16:31:44.552533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d40a2277918'
down_revision: Union[str, Sequence[str], None] = '736e4b523c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_default_owners',
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('default_owner_id', sa.UUID(), nullable=True),
    sa.Column('default_owner_team_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['default_owner_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_part_default_owners_category', 'part_default_owners', ['category'], unique=True, postgresql_where=sa.text('category IS NOT NULL'))
    op.create_index('uq_part_default_owners_fallback', 'part_default_owners', [sa.literal_column('(true)')], unique=True, postgresql_where=sa.text('category IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_part_default_owners_fallback', table_name='part_default_owners', postgresql_where=sa.text('category IS NULL'))
    op.drop_index('uq_part_default_owners_category', table_name='part_default_owners', postgresql_where=sa.text('category IS NOT NULL'))
    op.drop_table('part_default_owners')
    # ### end Alembic commands ###
