"""

Revision ID: 736e4b523c6c
Revises: f421a1a7dc04
Create Date: 2026-03-03 16:03:00.131407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736e4b523c6c'
down_revision: Union[str, Sequence[str], None] = 'f421a1a7dc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_default_assignments', sa.Column('default_owner_team_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('category_default_assignments_default_team_id_fkey'), 'category_default_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'category_default_assignments', 'teams', ['default_owner_team_id'], ['id'], ondelete='SET NULL')
    op.drop_column('category_default_assignments', 'default_team_id')
    op.add_column('parts', sa.Column('owner_team_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_parts_team_id'), table_name='parts')
    op.create_index('ix_parts_owner_team_id', 'parts', ['owner_team_id'], unique=False)
    op.drop_constraint(op.f('parts_team_id_fkey'), 'parts', type_='foreignkey')
    op.create_foreign_key(None, 'parts', 'teams', ['owner_team_id'], ['id'], ondelete='SET NULL')
    op.drop_column('parts', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.create_foreign_key(op.f('parts_team_id_fkey'), 'parts', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_parts_owner_team_id', table_name='parts')
    op.create_index(op.f('ix_parts_team_id'), 'parts', ['team_id'], unique=False)
    op.drop_column('parts', 'owner_team_id')
    op.add_column('category_default_assignments', sa.Column('default_team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category_default_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('category_default_assignments_default_team_id_fkey'), 'category_default_assignments', 'teams', ['default_team_id'], ['id'], ondelete='SET NULL')
    op.drop_column('category_default_assignments', 'default_owner_team_id')
    # ### end Alembic commands ###
