"""add description, created_at, updated_at to projects

Revision ID: 88a9be714609
Revises: 5e6e614bd2d0
Create Date: 2026-02-26 21:18:57.785977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a9be714609'
down_revision: Union[str, Sequence[str], None] = '5e6e614bd2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
