"""

Revision ID: a07b166edf66
Revises: baf391ce88bf
Create Date: 2026-03-01 13:04:49.204719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07b166edf66'
down_revision: Union[str, Sequence[str], None] = 'baf391ce88bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_request_reviewers',
    sa.Column('change_request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_request_id', 'user_id', name='uq_cr_reviewers_cr_id_user_id')
    )
    op.create_index('ix_cr_reviewers_change_request_id', 'change_request_reviewers', ['change_request_id'], unique=False)
    op.create_index('ix_cr_reviewers_user_id', 'change_request_reviewers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cr_reviewers_user_id', table_name='change_request_reviewers')
    op.drop_index('ix_cr_reviewers_change_request_id', table_name='change_request_reviewers')
    op.drop_table('change_request_reviewers')
    # ### end Alembic commands ###
