"""add project_parts table

Revision ID: db4f63b939b4
Revises: 88a9be714609
Create Date: 2026-02-26 21:52:04.681519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4f63b939b4'
down_revision: Union[str, Sequence[str], None] = '88a9be714609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'part_id', name='uq_project_parts_project_id_part_id')
    )
    op.create_index('ix_project_parts_part_id', 'project_parts', ['part_id'], unique=False)
    op.create_index('ix_project_parts_project_id', 'project_parts', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_parts_project_id', table_name='project_parts')
    op.drop_index('ix_project_parts_part_id', table_name='project_parts')
    op.drop_table('project_parts')
    # ### end Alembic commands ###
