"""

Revision ID: ef9911f1d0ca
Revises: 38ac9b805179
Create Date: 2026-03-01 22:28:44.099759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9911f1d0ca'
down_revision: Union[str, Sequence[str], None] = '38ac9b805179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('role', sa.String(length=20), nullable=False, server_default='MEMBER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'role')
    # ### end Alembic commands ###
