"""add onboarding fields to organizations and memberships

Revision ID: 151dc9a312ed
Revises: 98b923fcbb07
Create Date: 2026-02-10 23:48:25.515491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151dc9a312ed'
down_revision: Union[str, Sequence[str], None] = '98b923fcbb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('job_role', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('industry', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('team_size', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'team_size')
    op.drop_column('organizations', 'industry')
    op.drop_column('memberships', 'job_role')
    # ### end Alembic commands ###
