"""

Revision ID: 15c25b311855
Revises: 14e46b04a1c1
Create Date: 2026-03-01 12:35:22.862853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c25b311855'
down_revision: Union[str, Sequence[str], None] = '14e46b04a1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_image_file_key', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_file_key')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
