"""

Revision ID: 1c766b350a10
Revises: 6e115170000e
Create Date: 2026-03-01 14:10:20.944958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c766b350a10'
down_revision: Union[str, Sequence[str], None] = '6e115170000e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('profile_image_file_key', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'profile_image_file_key')
    # ### end Alembic commands ###
