"""add plan_type to organizations

Revision ID: 4ce9e0087a35
Revises: 151dc9a312ed
Create Date: 2026-02-11 00:34:05.242591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce9e0087a35'
down_revision: Union[str, Sequence[str], None] = '151dc9a312ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('plan_type', sa.String(length=20), nullable=False, server_default='FREE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'plan_type')
    # ### end Alembic commands ###
