"""

Revision ID: 70b4d441ca3e
Revises: 07db55921242
Create Date: 2026-02-27 19:17:10.585171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b4d441ca3e'
down_revision: Union[str, Sequence[str], None] = '07db55921242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('token_hash', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('uq_invitations_token'), 'invitations', type_='unique')
    op.create_unique_constraint('uq_invitations_token_hash', 'invitations', ['token_hash'])
    op.drop_column('invitations', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('token', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('uq_invitations_token_hash', 'invitations', type_='unique')
    op.create_unique_constraint(op.f('uq_invitations_token'), 'invitations', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('invitations', 'token_hash')
    # ### end Alembic commands ###
