"""move unique constraints to table_args

Revision ID: 8bc9246b5a57
Revises: f51518295dd8
Create Date: 2026-02-10 16:22:54.116353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc9246b5a57'
down_revision: Union[str, Sequence[str], None] = 'f51518295dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organizations_slug_key'), 'organizations', type_='unique')
    op.create_unique_constraint('uq_organizations_slug', 'organizations', ['slug'])
    op.drop_constraint(op.f('refresh_tokens_token_jti_key'), 'refresh_tokens', type_='unique')
    op.create_unique_constraint('uq_refresh_tokens_token_jti', 'refresh_tokens', ['token_jti'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_refresh_tokens_token_jti', 'refresh_tokens', type_='unique')
    op.create_unique_constraint(op.f('refresh_tokens_token_jti_key'), 'refresh_tokens', ['token_jti'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_organizations_slug', 'organizations', type_='unique')
    op.create_unique_constraint(op.f('organizations_slug_key'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
