"""add onboarded_at to organizations

Revision ID: e142bc82b123
Revises: 4ce9e0087a35
Create Date: 2026-02-11 23:28:24.194106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e142bc82b123'
down_revision: Union[str, Sequence[str], None] = '4ce9e0087a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'onboarded_at')
    # ### end Alembic commands ###
