"""add indexes for organizations and memberships

Revision ID: f51518295dd8
Revises: 69b4d193ff37
Create Date: 2026-02-10 15:45:20.174091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51518295dd8'
down_revision: Union[str, Sequence[str], None] = '69b4d193ff37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_memberships_org_id', 'memberships', ['org_id'], unique=False)
    op.create_index('ix_organizations_owner_id', 'organizations', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_owner_id', table_name='organizations')
    op.drop_index('ix_memberships_org_id', table_name='memberships')
    # ### end Alembic commands ###
